In [28]:
pip install requests==2.22.0 beautifulsoup4==4.8.1

  Found existing installation: beautifulsoup4 4.8.0
    Uninstalling beautifulsoup4-4.8.0:
      Successfully uninstalled beautifulsoup4-4.8.0
Note: you may need to restart the kernel to use updated packages.


In [1]:
from lxml import html
import requests

In [12]:
##page = requests.get('DO_DUMP.html')'
with open(r'DO_DUMP.html', "r", encoding='utf-8') as f:
    page = f.read()
tree = html.fromstring(page)

In [47]:
## Testing
import re
test ='<span class="chatlog__author-name" title="Blacknium#7206" data-user-id="415234448536109056" style="color: rgb(4,129,170)">Blacknium</span>'
##title_search = re.search('(<span class=\"chatlog__author-name\" title=\".*\>)(.*)(<\/span)', html, re.IGNORECASE)

title_search = re.search(r'(<span class=\"chatlog__author-name\" title=\".*\>)(.*)(<\/span)', test, re.IGNORECASE)
if title_search:
    title = title_search.group(2)
    print(title)
    
att_search = re.search(r'(<img class=\"chatlog__attachment-thumbnail\" src=")(.*)(" alt.*)', test, re.IGNORECASE)

if att_search:
    title = att_search.group(2)
    print(title)

dt_search =  re.search(r'(<span class="chatlog__timestamp">)(.*)(<.*)', line, re.IGNORECASE)
if dt_search:
    dt = dt_search.group(2)
    print(dt)

    

Blacknium


In [75]:
import re

with open(r'DO_DUMP.html', "r", encoding='ascii', errors='ignore') as f:
    for line in f:

        auth_search = re.search(r'(<span class=\"chatlog__author-name\" title=\".*\>)(.*)(<\/span)', line, re.IGNORECASE)
        if auth_search:
            auth = auth_search.group(2)
            #print(auth)
            k = open("out.txt", "a")
            k.write("|"+auth + "\r")
            k.close()
            
        dt_search = re.search(r'(<span class="chatlog__timestamp">)(.*)(<.*)', line, re.IGNORECASE)
        if dt_search:
            dt = dt_search.group(2)
            #print(dt)
            k = open("out.txt", "a")
            k.write(dt + "\r")
            k.close()

            
        att_search = re.search(r'(<img class=\"chatlog__attachment-thumbnail\" src=")(.*)(" alt.*)', line, re.IGNORECASE)

        if att_search:
            att = att_search.group(2)
            #print(att)
            k = open("out.txt", "a")
            k.write(att + "\r")
            k.close()


In [76]:
# Importing Required Modules
import sys
import requests
from PIL import Image

# Exception Handling for invalid requests
try:
        # Creating an request object to store the response
        # The URL is refrenced sys.argv[1]
  ImgRequest = requests.get(sys.argv[1])

        # Verifying whether the specified URL exist or not
  if ImgRequest.status_code == requests.codes.ok:

                # Opening a file to write bytes from response content
                # Storing this onject as an image file on the hard drive
    img = open("https://cdn.discordapp.com/attachments/677197132968755207/685217851967406086/Screenshot_20200305-220730.png","wb")
    img.write(ImgRequest.content)
    img.close()

                # Opening Inage file using PIL Image
    img = Image.open("https://cdn.discordapp.com/attachments/677197132968755207/685217851967406086/Screenshot_20200305-220730.png")
    img.show()
  else:
    print(ImgRequest.status_code)

except Exception as e:
  print(str(e))

Invalid URL '-f': No schema supplied. Perhaps you meant http://-f?


In [118]:
from PIL import Image
import requests
from io import BytesIO

#test
#response = requests.get("https://cdn.discordapp.com/attachments/677197132968755207/685217851967406086/Screenshot_20200305-220730.png")

response = requests.get("https://cdn.discordapp.com/attachments/677197132968755207/677198291586252919/Screenshot_20200212-180159_Video_Player.jpg")

img = Image.open(BytesIO(response.content))

im2_crop = img.crop((1000, 90, 1750, 775))
im2_crop.save('test_crop.png', quality=95)

im2 = Image.open('test_crop.png')
im2.show
print(pytesseract.image_to_string(im2))



In [119]:
from PIL import Image
import requests
from io import BytesIO


#pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'


#test
#response = requests.get("https://cdn.discordapp.com/attachments/677197132968755207/685217851967406086/Screenshot_20200305-220730.png")

response = requests.get("https://cdn.discordapp.com/attachments/677197132968755207/677198291900956672/Screenshot_20200212-180205_Video_Player.jpg")

img = Image.open(BytesIO(response.content))

im2_crop = img.crop((1000, 90, 1750, 775))
im2_crop.save('test_crop2.png', quality=95)

im2 = Image.open('test_crop2.png')
im2.show

print(pytesseract.image_to_string(im2))


In [112]:
def ocr_core(filename):
    
    pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
    """
    This function will handle the core OCR processing of images.
    
    """
    text = pytesseract.image_to_string(Image.open(filename))  # We'll use Pillow's Image class to open the image and pytesseract to detect the string in the image
    return text


In [10]:
# Python program to illustrate  
# template matching 
from PIL import Image
import cv2 
import numpy as np 
import requests
from io import BytesIO
  
# Read the main image 
#img_rgb = cv2.imread('mainimage.jpg'). 
response = requests.get("https://cdn.discordapp.com/attachments/677197132968755207/677198291586252919/Screenshot_20200212-180159_Video_Player.jpg")

img = Image.open(BytesIO(response.content))

img.save('aaa.jpeg')
img_rgb = Image.open('aaa.jpeg')


#img_rgb.show()

#img = cv2.imread('messi5.jpg',0)

# Convert it to grayscale 
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY) 
  
# Read the template 
template = cv2.imread('Template_Offer.png',0) 
  
# Store width and height of template in w and h 
w, h = template.shape[::-1] 
  
# Perform match operations. 
res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED) 
  
# Specify a threshold 
threshold = 0.8
  
# Store the coordinates of matched area in a numpy array 
loc = np.where( res >= threshold)  
  
# Draw a rectangle around the matched region. 
for pt in zip(*loc[::-1]): 
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,255,255), 2) 
  
# Show the final image with the matched area. 
cv2.imshow('Detected',img_rgb) 

TypeError: Expected Ptr<cv::UMat> for argument 'src'

In [43]:
import cv2
import numpy as np
#open the main image and convert it to gray scale image
main_image = cv2.imread('aaa.png')
gray_image = cv2.cvtColor(main_image, cv2.COLOR_BGR2GRAY)
#open the template as gray scale image
template = cv2.imread('Template_Offer.png', 0)
width, height = template.shape[::-1] #get the width and height
#match the template using cv2.matchTemplate
match = cv2.matchTemplate(gray_image, template, cv2.TM_CCOEFF_NORMED)
threshold = 0.8
position = np.where(match >= threshold) #get the location of template in the image
for point in zip(*position[::-1]): #draw the rectangle around the matched template
       cv2.rectangle(main_image, point, (point[0] + width, point[1] + height), (0, 204, 153), 0)
cv2.imshow('Template Found', main_image)
cv2.waitKey(0)

-1

In [3]:
import imutils
import cv2
import numpy as np
#Open template and get canny
template = cv2.imread('\Template_Offer.png',0)
print(template)
template = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)
template = cv2.Canny(template, 10, 25)
(height, width) = template.shape[:2]
#open the main image and convert it to gray scale image
main_image = cv2.imread('aaa.png')
gray_image = cv2.cvtColor(main_image, cv2.COLOR_BGR2GRAY)
temp_found = None
for scale in np.linspace(0.2, 1.0, 20)[::-1]:
   #resize the image and store the ratio
    resized_img = imutils.resize(gray_image, width = int(gray_image.shape[1] * scale))
    ratio = gray_image.shape[1] / float(resized_img.shape[1])
if resized_img.shape[0] < height or resized_img.shape[1] < width:
#break
#Convert to edged image for checking
    e = cv2.Canny(resized_img, 10, 25)
match = cv2.matchTemplate(e, template, cv2.TM_CCOEFF)
(_, val_max, _, loc_max) = cv2.minMaxLoc(match)
if temp_found is None or val_max>temp_found[0]:
      temp_found = (val_max, loc_max, ratio)
#Get information from temp_found to compute x,y coordinate
(_, loc_max, r) = temp_found
(x_start, y_start) = (int(loc_max[0]), int(loc_max[1]))
(x_end, y_end) = (int((loc_max[0] + width)), int((loc_max[1] + height)))
#Draw rectangle around the template
cv2.rectangle(main_image, (x_start, y_start), (x_end, y_end), (153, 22, 0), 5)
cv2.imshow('Template Found', main_image)
cv2.waitKey(0)

None


error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [53]:
template = cv2.imread('Template_Offer.png')
#print(template)

cv2.imshow('image',template)


[[[57 60 64]
  [59 62 66]
  [55 58 62]
  ...
  [60 62 62]
  [60 62 62]
  [59 61 61]]

 [[59 62 66]
  [60 63 67]
  [62 65 69]
  ...
  [61 63 63]
  [59 61 61]
  [59 61 61]]

 [[59 62 66]
  [59 62 66]
  [59 62 66]
  ...
  [60 62 62]
  [61 63 63]
  [58 60 60]]

 ...

 [[70 70 64]
  [67 67 61]
  [56 56 50]
  ...
  [73 71 61]
  [72 70 60]
  [73 71 61]]

 [[70 70 64]
  [69 69 63]
  [70 70 64]
  ...
  [74 72 62]
  [71 69 59]
  [74 72 62]]

 [[70 70 64]
  [71 71 65]
  [71 71 65]
  ...
  [73 71 61]
  [73 71 60]
  [73 71 60]]]


In [1]:

import cv2 # import opencv
 
# load image 
image = cv2.imread('aaa.png')
 
# press 'q' to exit while loop
while True: 
    # display the image and wait for key press
    cv2.imshow("Original Image", image)
    key = cv2.waitKey()
 
    # if 'a' is pressed, draw roi on copy image
    if key == ord('a'):
        (x,y,w,h) = cv2.selectROI("Image", image, fromCenter=False, 
            showCrosshair=False)
        # make sure an area is selected before pressing 'enter', 'space' or 'q'
        # crop the image and display cropped image
        cropped_roi = image[y:y+h, x:x+w]
        cv2.imshow("Cropped", cropped_roi)
        
        # print y, x coordinates for roi, and width and height of selected roi
        print("Coordinates: ({}, {}), Width: {}, Height: {}".format(y, x, w, h))
    elif key == ord('q'):
        break

cv2.destroyAllWindows()

Coordinates: (292, 963), Width: 136, Height: 137


KeyboardInterrupt: 

In [2]:
import cv2

#Load the image in black and white (0 - b/w, 1 - color).
img = cv2.imread('aaa.png', 0)

#Get the height and width of the image.
h, w = img.shape[:2]

#Invert the image to be white on black for compatibility with findContours function.
imgray = 255 - img
#Binarize the image and call it thresh.
ret, thresh = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY)

#Find all the contours in thresh. In your case the 3 and the additional strike
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#Calculate bounding rectangles for each contour.
rects = [cv2.boundingRect(cnt) for cnt in contours]

#Calculate the combined bounding rectangle points.
top_x = min([x for (x, y, w, h) in rects])
top_y = min([y for (x, y, w, h) in rects])
bottom_x = max([x+w for (x, y, w, h) in rects])
bottom_y = max([y+h for (x, y, w, h) in rects])

#Draw the rectangle on the image
out = cv2.rectangle(img, (top_x, top_y), (bottom_x, bottom_y), (0, 255, 0), 2)
#Save it as out.jpg
cv2.imwrite('out.jpg', img)

True

In [1]:
import cv2 
  
# path 
path = r'\aaa.png'
  
# Using cv2.imread() method 
# Using 0 to read image in grayscale mode 
img = cv2.imread(path, 0) 
  
# Displaying the image 
cv2.imshow('image', img) 

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [1]:
import cv2
import numpy as np
#open the main image and convert it to gray scale image
main_image = cv2.imread('aaa.png')
gray_image = cv2.cvtColor(main_image, cv2.COLOR_BGR2GRAY)
#open the template as gray scale image
template = cv2.imread('Template_Offer.png', 0)
width, height = template.shape[::-1] #get the width and height
#match the template using cv2.matchTemplate
match = cv2.matchTemplate(gray_image, template, cv2.TM_CCOEFF_NORMED)
threshold = 0.8
position = np.where(match >= threshold) #get the location of template in the image
for point in zip(*position[::-1]): #draw the rectangle around the matched template
       cv2.rectangle(main_image, point, (point[0] + width, point[1] + height), (0, 204, 153), 0)
cv2.imshow('Template Found', main_image)
cv2.waitKey(0)

113